export const sizes = [
  {
    id: 1,
    label: "Pequeño",
    value: "small",
    price: 10,
    approximateSize: 20,
    unit: "cm",
    isActive: false,
  },
  {
    id: 2,
    label: "Mediano",
    value: "medium",
    price: 35,
    approximateSize: 40,
    unit: "cm",
    isActive: false,
  },
  {
    id: 3,
    label: "Grande",
    value: "large",
    price: 70,
    approximateSize: 80,
    unit: "cm",
    isActive: true,
  },
  {
    id: 4,
    label: "Gigante",
    value: "extra-large",
    price: 100,
    approximateSize: 120,
    unit: "cm",
    isActive: true,
  },
]
